"""Initial migration - create all tables

Revision ID: 27248a9babc8
Revises: 
Create Date: 2026-02-27 10:48:06.382543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27248a9babc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_group_types',
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age_class', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species', 'breed', 'sex', 'age_class', name='uq_animal_group_type')
    )
    op.create_table('farms',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('mobs',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'name', name='uq_mob_farm_name')
    )
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mobs_farm_id'), ['farm_id'], unique=False)

    op.create_table('movement_events',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_kind', sa.Enum('move', 'split', 'merge', name='movementeventkind'), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_events_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_events_farm_id'), ['farm_id'], unique=False)

    op.create_table('paddocks',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grazeable_area_ha', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'name', name='uq_paddock_farm_name')
    )
    with op.batch_alter_table('paddocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paddocks_farm_id'), ['farm_id'], unique=False)

    op.create_table('rainfall_records',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mm >= 0', name='ck_rainfall_non_negative'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rainfall_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rainfall_records_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rainfall_records_recorded_on'), ['recorded_on'], unique=False)

    op.create_table('user_farm_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'farm_id', name='uq_user_farm_role')
    )
    with op.batch_alter_table('user_farm_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_farm_roles_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_farm_roles_user_id'), ['user_id'], unique=False)

    op.create_table('animal_group_balances',
    sa.Column('mob_id', sa.String(length=36), nullable=False),
    sa.Column('animal_group_type_id', sa.String(length=36), nullable=False),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('head_count >= 0', name='ck_balance_non_negative'),
    sa.ForeignKeyConstraint(['animal_group_type_id'], ['animal_group_types.id'], ),
    sa.ForeignKeyConstraint(['mob_id'], ['mobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mob_id', 'animal_group_type_id', name='uq_mob_group_balance')
    )
    with op.batch_alter_table('animal_group_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_group_balances_animal_group_type_id'), ['animal_group_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_group_balances_mob_id'), ['mob_id'], unique=False)

    op.create_table('daily_stock_snapshots',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('paddock_id', sa.String(length=36), nullable=True),
    sa.Column('animal_group_type_id', sa.String(length=36), nullable=False),
    sa.Column('head_count', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['animal_group_type_id'], ['animal_group_types.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['paddock_id'], ['paddocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'snapshot_date', 'paddock_id', 'animal_group_type_id', name='uq_daily_stock_snapshot')
    )
    with op.batch_alter_table('daily_stock_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stock_snapshots_animal_group_type_id'), ['animal_group_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_stock_snapshots_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_stock_snapshots_paddock_id'), ['paddock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_stock_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('grazing_sessions',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('mob_id', sa.String(length=36), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['mob_id'], ['mobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grazing_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grazing_sessions_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grazing_sessions_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grazing_sessions_mob_id'), ['mob_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grazing_sessions_start_at'), ['start_at'], unique=False)

    op.create_table('mob_lineage',
    sa.Column('parent_mob_id', sa.String(length=36), nullable=False),
    sa.Column('child_mob_id', sa.String(length=36), nullable=False),
    sa.Column('movement_event_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_mob_id'], ['mobs.id'], ),
    sa.ForeignKeyConstraint(['movement_event_id'], ['movement_events.id'], ),
    sa.ForeignKeyConstraint(['parent_mob_id'], ['mobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mob_lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mob_lineage_child_mob_id'), ['child_mob_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mob_lineage_movement_event_id'), ['movement_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mob_lineage_parent_mob_id'), ['parent_mob_id'], unique=False)

    op.create_table('movement_event_mobs',
    sa.Column('movement_event_id', sa.String(length=36), nullable=False),
    sa.Column('mob_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('source', 'target', 'result', name='movementrole'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mob_id'], ['mobs.id'], ),
    sa.ForeignKeyConstraint(['movement_event_id'], ['movement_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement_event_mobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_event_mobs_mob_id'), ['mob_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movement_event_mobs_movement_event_id'), ['movement_event_id'], unique=False)

    op.create_table('stock_ledger_entries',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('mob_id', sa.String(length=36), nullable=False),
    sa.Column('animal_group_type_id', sa.String(length=36), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('birth', 'purchase', 'transfer_in', 'adjustment_in', 'death', 'sale', 'missing', 'transfer_out', 'adjustment_out', name='stockeventtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_stock_quantity_positive'),
    sa.ForeignKeyConstraint(['animal_group_type_id'], ['animal_group_types.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['mob_id'], ['mobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_animal_group_type_id'), ['animal_group_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entries_mob_id'), ['mob_id'], unique=False)

    op.create_table('grazing_allocations',
    sa.Column('grazing_session_id', sa.String(length=36), nullable=False),
    sa.Column('paddock_id', sa.String(length=36), nullable=False),
    sa.Column('allocation_fraction', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocation_fraction > 0 and allocation_fraction <= 1', name='ck_allocation_fraction'),
    sa.ForeignKeyConstraint(['grazing_session_id'], ['grazing_sessions.id'], ),
    sa.ForeignKeyConstraint(['paddock_id'], ['paddocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grazing_session_id', 'paddock_id', name='uq_session_paddock')
    )
    with op.batch_alter_table('grazing_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grazing_allocations_grazing_session_id'), ['grazing_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grazing_allocations_paddock_id'), ['paddock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grazing_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grazing_allocations_paddock_id'))
        batch_op.drop_index(batch_op.f('ix_grazing_allocations_grazing_session_id'))

    op.drop_table('grazing_allocations')
    with op.batch_alter_table('stock_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_mob_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_farm_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_event_time'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entries_animal_group_type_id'))

    op.drop_table('stock_ledger_entries')
    with op.batch_alter_table('movement_event_mobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_event_mobs_movement_event_id'))
        batch_op.drop_index(batch_op.f('ix_movement_event_mobs_mob_id'))

    op.drop_table('movement_event_mobs')
    with op.batch_alter_table('mob_lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mob_lineage_parent_mob_id'))
        batch_op.drop_index(batch_op.f('ix_mob_lineage_movement_event_id'))
        batch_op.drop_index(batch_op.f('ix_mob_lineage_child_mob_id'))

    op.drop_table('mob_lineage')
    with op.batch_alter_table('grazing_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grazing_sessions_start_at'))
        batch_op.drop_index(batch_op.f('ix_grazing_sessions_mob_id'))
        batch_op.drop_index(batch_op.f('ix_grazing_sessions_farm_id'))
        batch_op.drop_index(batch_op.f('ix_grazing_sessions_end_at'))

    op.drop_table('grazing_sessions')
    with op.batch_alter_table('daily_stock_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stock_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_daily_stock_snapshots_paddock_id'))
        batch_op.drop_index(batch_op.f('ix_daily_stock_snapshots_farm_id'))
        batch_op.drop_index(batch_op.f('ix_daily_stock_snapshots_animal_group_type_id'))

    op.drop_table('daily_stock_snapshots')
    with op.batch_alter_table('animal_group_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_group_balances_mob_id'))
        batch_op.drop_index(batch_op.f('ix_animal_group_balances_animal_group_type_id'))

    op.drop_table('animal_group_balances')
    with op.batch_alter_table('user_farm_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_farm_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_farm_roles_farm_id'))

    op.drop_table('user_farm_roles')
    with op.batch_alter_table('rainfall_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rainfall_records_recorded_on'))
        batch_op.drop_index(batch_op.f('ix_rainfall_records_farm_id'))

    op.drop_table('rainfall_records')
    with op.batch_alter_table('paddocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paddocks_farm_id'))

    op.drop_table('paddocks')
    with op.batch_alter_table('movement_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_events_farm_id'))
        batch_op.drop_index(batch_op.f('ix_movement_events_event_time'))

    op.drop_table('movement_events')
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobs_farm_id'))

    op.drop_table('mobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('farms')
    op.drop_table('animal_group_types')
    # ### end Alembic commands ###
